apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nabiz-data
  namespace: nabiz
  labels:
    app.kubernetes.io/name: nabiz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
