apiVersion: v1
kind: Service
metadata:
  name: nabiz
  namespace: nabiz
  labels:
    app.kubernetes.io/name: nabiz
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nabiz
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
